base: &base

  # Training config
  weight_init: {conv_init: 'normal', conv_scale: 0.02, conv_bias: 0.}
  lr: 1E-4
  lambda_rho: 1E-2 # weight for additional rho loss term
  batch_size: 1
  num_epochs: 2
  enable_amp: False
  enable_ndhwc: False
  enable_apex: False
  ngpu: 1
  expdir: '/results'

  # Data
  data_loader_config: 'synthetic' # choices: 'synthetic', 'inmem', 'lowmem', 'dali-inmem'
  box_size: 512 # total size of simulation box
  data_size: 256 # size of crops for training
  num_data_workers: 2 # number of dataloader worker threads per proc
  N_out_channels: 5
  train_path: None
  val_path: None
  use_cache: None # set this to a cache dir (e.g., NVMe on CoriGPU) if you copied data there


withAMP:
  <<: *base
  enable_amp: True

multi8: 
  <<: *base
  ngpu: 8

cosmo: &cosmo
  <<: *base
  data_loader_config: 'lowmem'
  train_path: '/data/normalized1024_z3_alt_bigcrop_transp.h5'
  val_path: '/data/normalized1024_z3_alt_bigcrop2_transp.h5'
  use_cache: None # '/tmp/'
  Nsamples: 100 #1000
  Nsamples_val: 20 #64
  num_epochs: 5

cosmo-AMP: &cosmo_amp
  <<: *cosmo
  enable_amp: True

cosmo-AMP-APEX:
  <<: *cosmo_amp
  enable_apex: True

cosmo-AMP-NDHWC:
  <<: *cosmo_amp
  enable_ndhwc: True

cosmo-dali: &cosmo_dali
  <<: *base
  data_loader_config: 'dali-inmem'
  train_path: '/data/normalized1024_z3_alt_bigcrop.h5'
  val_path: '/data/normalized1024_z3_alt_bigcrop2.h5'
  use_cache: None # '/tmp/'
  Nsamples: 100 #1000
  Nsamples_val: 20 #64
  num_epochs: 5

cosmo-dali-AMP: &cosmo_dali_amp
  <<: *cosmo_dali
  enable_amp: True

cosmo-dali-AMP-APEX:
  <<: *cosmo_dali_amp
  enable_apex: True
    
cosmo-dali-AMP-NDHWC:
  <<: *cosmo_dali_amp
  enable_ndhwc: True

cosmo-dali-lomem: &cosmo_dali_lomem
  <<: *base
  data_loader_config: 'dali-lomem'
  train_path: '/data/normalized1024_z3_alt_bigcrop_data.npy'
  train_path_label: '/data/normalized1024_z3_alt_bigcrop_label.npy'
  val_path: '/data/normalized1024_z3_alt_bigcrop2_data.npy'
  val_path_label: '/data/normalized1024_z3_alt_bigcrop2_label.npy'
  use_cache: None # '/tmp/'
  Nsamples: 100 #1000
  Nsamples_val: 20 #64
  num_epochs: 5

cosmo-dali-lomem-AMP: &cosmo_dali_lomem_amp
  <<: *cosmo_dali_lomem
  enable_amp: True

cosmo-dali-lomem-AMP-NDHWC:
  <<: *cosmo_dali_lomem_amp
  enable_ndhwc: True

cosmo_small:
  <<: *base
  data_loader_config: 'lowmem'
  train_path: '/data/ampUnet/normalized1024_z3_alt_bigcrop_transp.h5'
  val_path: '/data/ampUnet/normalized1024_z3_alt_bigcrop2_transp.h5'
  use_cache: None #'/tmp/'
  data_size: 128
  Nsamples: 1000
  Nsamples_val: 256
  num_epochs: 20
